apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus_1
    url: http://prometheus:9090
    jsonData:
      timeInterval: '1s'
    version: 1
    editable: false
